#!/bin/sh
PIDFILE=perfd.pid
TACFILE=torperfd
LOGFILE=perfd.log
USER=debian-tor
GROUP=debian-tor

case "$1" in
  start)
    if [ -f $PIDFILE ]; then
      echo "Perfd is already running!"
      exit 1
    fi
    echo "Starting Perfd."
    twistd --uid $USER --gid $GROUP -l $LOGFILE --prefix "perfd" --pidfile $PIDFILE $TACFILE
    ;;
  restart)
    if [ -f $PIDFILE ]; then
      echo "Stopping Perfd."
      kill `head -1 $PIDFILE`
      rm $PIDFILE
    fi
    echo "Restarting Perfd."
    twistd --uid $USER --gid $GROUP -l $LOGFILE --prefix "perfd" --pidfile $PIDFILE $TACFILE
    ;;
  stop)
    if [ ! -f $PIDFILE ]; then
      echo "Perfd is not running!"
      exit 1
    fi
    echo "Stopping Perfd."
    kill `head -1 $PIDFILE`
    rm $PIDFILE
    ;;
  *)
    echo "Usage: "$0" {start|restart|stop}"
    exit 1
    ;;
esac

exit 0

