#!/bin/sh
PIDFILE=perfd.pid
TACFILE=torperfd
LOGFILE=perfd.log
USER=admin
GROUP=admin
HOSTIP=23.22.45.179

case "$1" in
  start)
    if [ -f $PIDFILE ]; then
      echo "Perfd is already running!"
      exit 1
    fi
    echo "Starting Perfd."
    twistd --uid $USER --gid $GROUP -l $LOGFILE --prefix "perfd" --pidfile $PIDFILE $TACFILE -h $HOSTIP
    ;;
  restart)
    if [ -f $PIDFILE ]; then
      echo "Stopping Perfd."
      kill `head -1 $PIDFILE`
    fi
    echo "Restarting Perfd."
    twistd --uid $USER --gid $GROUP -l $LOGFILE --prefix "perfd" --pidfile $PIDFILE $TACFILE -h $HOSTIP
    ;;
  stop)
    if [ ! -f $PIDFILE ]; then
      echo "Perfd is not running!"
      exit 1
    fi
    echo "Stopping Perfd."
    kill `head -1 $PIDFILE`
    ;;
  *)
    echo "Usage: "$0" {start|restart|stop}"
    exit 1
    ;;
esac

exit 0

